zapatacomputing/benchq

- README.md
This PR adds a link to the DARPA Quantum Benchmarking website to the README to better acknowledge the program's support.
> Adding link to DARPA site

- src/benchq/resource_estimation/graph_compilation.py
We fix the way the max graph degree is calculated when dealing with subcircuits.
> Update max_graph_degree bound

- src/benchq/data_structures/quantum_program.py
- src/benchq/resource_estimation/graph_compilation.py
Two improvements coming from our recent work on the demo:
- using max node degree and number of measurements steps  for resource estimations
- adding option to generate full circuit from QuantumProgram
> Update resource estimates

- examples/qsp_vlasov.py
Updated the QSP Vlasov example, now it serves a dual role:
1. Gives an example of how one can use Bench-Q for estimating Vlasov Hamiltonian
2. Gives an example of three modes of operation for graph state compilation.
> refactor(qsp_vlasov.py): Refactor the vlasov example

- setup.cfg
New version of pyLIQTR has been released so we can get rid of the dependency which uses a custom commit.
> Update pyLIQTR dependency

- examples/advanced_estimates.py
- examples/orquestra/hydrogen_demo/defs.py
- src/benchq/problem_ingestion/hamiltonian_generation.py
Advanced example code was not properly adjusted after recent changes. This should fix it
> Fix: Fix advanced example

- setup.cfg
- src/benchq/problem_ingestion/molecule_instance_generation.py
- tests/benchq/problem_ingestion/test_molecule_instance_generation.py
This PR allows Hamiltonians to be generated for chemistry application instances that use AVAS to reduce the active space.
> Support AVAS in Hamiltonian generation

- src/benchq/algorithms/_qsp.py
- tests/benchq/algorithms/test_qsp.py
- Context: why is it needed? In case of bug, what was the cause for the bug?
- Concise description of the implemented solution.
- If any dependencies are added, list them and justify why they are needed.
> Removed using deprecated methods from pyLIQTR.

- examples/qsp_vlasov.py
- src/benchq/algorithms/_qsp.py
- src/benchq/data_structures/quantum_program.py
- src/benchq/resource_estimation/v2/__init__.py
- src/benchq/resource_estimation/v2/estimators.py
- src/benchq/resource_estimation/v2/pipelines.py
- src/benchq/resource_estimation/v2/structs.py
- src/benchq/resource_estimation/v2/transformers.py
- Context: why is it needed? In case of bug, what was the cause for the bug?
- Concise description of the implemented solution.
- If any dependencies are added, list them and justify why they are needed.
> Refactor transformers

- src/benchq/resource_estimation/graph/estimators.py
This changes name of several methods and variables to better match the description from Simon's email.
> Change naming of some methods/variables in GraphResourceEstimator

- src/benchq/resource_estimation/graph/estimators.py
This PR adjusts several formulas and instroduces names for some intermediate variables to hopefully make our `GraphResourceEstimator` code more readable.
> Adjustments after call with Simon

- README.md
- examples/advanced_estimates.py
- examples/advanced_estimates_microsoft.py
- examples/orquestra/hydrogen_demo/estimates_ms.py
- examples/packages_comparison.py
- examples/re_sw_comparison.py
- setup.cfg
- src/benchq/resource_estimation/azure.py
- src/benchq/resource_estimation/graph/estimators.py
- tests/benchq/resource_estimation/test_azure_re.py
Updated and refactored integration with Azure QRE
> Dta 128/azure update

- examples/ex_1_from_qasm.py
- Context: I was trying to run the example and got a path error. This fix solved it
> fix: small data path error

- src/benchq/problem_embeddings/_qsp.py
When mapping named qubits to line qubits during QSP program construction we considered each circuit in isolation. This might result in two different subroutines operating on a common set of qubits having different qubit mappings, producing incorrect results.
The particular order and types of subroutines that we construct now cause the problem to not be visible, but it would become apparent later when we improve `select_v` decomposition.
> fix: implement qubit remapping so it takes into account all circuits at once

- src/benchq/compilation/graph_sim_mini.jl
- tests/benchq/resource_estimation/test_extrapolation_estimator.py
- tests/benchq/resource_estimation/test_graph_estimator.py
Eliminate the need to do some local complements by allowing for lcos which commute with CZ. Will provide a small speedup in some cases.
> feat: small performance improvement

- src/benchq/algorithms/lde_solver.py
* Preparation of the COEF_k and COEF_k_prime quantum states
* Implementation of C-PREP unitaries
> ZQS-1334: Add COEF_k and PREP

- examples/ex_8_remote_mlflow/defs.py
- examples/ex_8_remote_mlflow/run.py
- Context: With the new mlflow helper functions in 586c696d469ca9293e38bde76ff88267772cd47c users should have an example of using them
- This example was copied and modified from example 5 which presents using benchq on orquestra without mlflow. I decided to conventional commit this as `docs:` because benchq currently doesn't have docs so examples are about all the docs users get
> docs: add new mlflow demo

- Makefile
- Now coverage reports say we're consistently hitting 80%+, so I figure it would be good to start enforcing 75%+ just to have a bit of wiggle room.
> test: increase min coverage to 75

- .github/workflows/build-python-wheel-via-cicd-actions.yaml
- setup.cfg
New workflow that pushes benchq into PyPi on each github release.
> Feat: Workflow to release benchq to PyPi

- .github/workflows/performance_test.yml
- benchmarks/test_get_qsp_program.py
- setup.cfg
Allows to run performance tests - results will appear in Github Page
> Feat: Performance testing github workflow

- .github/workflows/performance_test.yml
workflow_dispatch trigger is broken on performance test workflow. We have to switch to on-push
> Change workflow trigger on performance tests

- src/benchq/algorithms/lde_solver.py
- src/benchq/algorithms/lin_and_dong_qsp.py
- tests/benchq/algorithms/test_lde_solver.py
- Implementation of the QSP in qiskit (qsp.py).
-  Added the estimation of the parameters for quantum DE solver: number of grid points, matrix condition number, degree of approximating polynomial.
-  Construction of the inverse of block encoding (SEL_inv) using the QSP circuit construction.
> ZQS-1336: Inverse of Block Encoding

- src/benchq/algorithms/lde_solver.py
- tests/benchq/algorithms/test_lde_solver.py
* Constructs Matrix Exponentiation Circuit (f(x)=e^x)
*  Basic tests
> ZQS-1338: Construct block encoding for e^A

- examples/ex_10_lde_solver.py
- src/benchq/algorithms/lde_solver.py
- tests/benchq/algorithms/test_lde_solver.py
* Implementation of time-marching circuit construction algorithm
* Implementation of Uniform Singular Value Amplification procedure
* Construction of a time-marching circuit using the Uniform Singular Value Amplification and the Compression Gadget
* Added basic tests
* Added a tutorial on how to run the LDE solver and count the number of T and T_dag  gates
> ZQS-1340_and_ZQS-1361: Construct time marching circuit using the USVA

- examples/ex_7_mlflow.py
- examples/ex_8_remote_mlflow/defs.py
- src/benchq/data_structures/__init__.py
- src/benchq/data_structures/hardware_architecture_models.py
- src/benchq/data_structures/resource_info.py
- src/benchq/resource_estimation/graph/graph_estimator.py
- src/benchq/resource_estimation/openfermion_re.py
- tests/benchq/data_structures/test_hardware_architecture_models.py
- tests/benchq/resource_estimation/test_graph_estimator.py
- Context: why is it needed? In case of bug, what was the cause for the bug?
- Concise description of the implemented solution.
- If any dependencies are added, list them and justify why they are needed.
> Feat: Add hardware estimates if detailed HW model is provided

- src/benchq/data_structures/quantum_program.py
- src/benchq/resource_estimation/default_pipelines.py
Automatic resource estimator was out of date. To make it more useful the numbers should be adjusted to the current performance level of benchq.
> Feat: Refresh automatic resource estimator

- Makefile
- pyproject.toml
- setup.cfg
- src/benchq/algorithms/data_structures/algorithm_implementation.py
- src/benchq/algorithms/gsee/qpe_gsee.py
- src/benchq/algorithms/time_evolution.py
- src/benchq/compilation/transpile_to_native_gates.py
- src/benchq/problem_embeddings/qpe.py
- src/benchq/quantum_hardware_modeling/hardware_architecture_models.py
- src/benchq/resource_estimators/graph_estimators/graph_estimator.py
Pyright is a type checking tool that would be beneficial to use for a few reasons:
* It can catch errors that mypy will miss.
* It often is much faster than mypy.
* Other Zapata projects are now using it.
This PR fixes a few typing issues found by pyright and also adds it as a required check (but with a number of submodules excluded for the time being). This strategy is inspired by the approach taken by the Orquestra SDK, see https://github.com/zapatacomputing/orquestra-workflow-sdk/pull/352.
> Typing improvements
