examples/advanced_estimates.py, examples/h_chain_trotter.py, examples/orquestra/hydrogen_demo/defs.py, examples/qsp_vlasov.py, src/benchq/problem_ingestion/__init__.py, src/benchq/problem_ingestion/hamiltonian_generation.py, src/benchq/problem_ingestion/molecule_instance_generation.py, tests/benchq/problem_ingestion/test_molecule_instance_generation.py
The chemistry application instances had some code duplication and inconsistent patterns. This PR addresses this by introducing a `ChemistryApplicationInstance` dataclass based on discussion with @aakunitsa and @mkodrycka. The dataclass encapsulates the information that defines an application instance, such as geometry, charge, and active space.
=> Refactor chemistry application instances

src/benchq/resource_estimation/graph_compilation.py, tests/benchq/resource_estimation/test_graph_compilation.py
This PR adds some tests that verify that the resource estimations for graph state compilation are correct for some simple cases.
It would be good if the reviewer could take a look at the expected `n_measurement_steps` for `test_get_resource_estimations_for_program_gives_correct_results` and make sure they make sense.
Also @mstechly note that instead of making a test with RZ at some angle besides pi/4, I added instead a test that combines RX and RY. The reason is that I don't know of any rotation angle for which we can get an exact Clifford + T decomposition of RZ (besides the trivial ones that require zero or one T gates).
=> test: Add tests for graph compilation resource estimation

setup.cfg, src/benchq/problem_ingestion/molecule_instance_generation.py, tests/benchq/problem_ingestion/test_molecule_instance_generation.py
This PR addresses two issues: first, the hydrogen chain problem instance currently sets the spin multiplicity to a value that does not correspond to the ground state. Second, the high spin multiplicities required by long hydrogen chains require a modified version of openfermion to be used.
To address this, this PR changes the spin multiplicity of the hydrogen chain application instance to be 1 for even numbers of hydrogen atoms and 2 for odd numbers of hydrogen atoms. (See [Motta et al.](https://journals.aps.org/prx/pdf/10.1103/PhysRevX.10.031058) for details on the ground state of the hydrogen chain.) The dependencies are also updated to remove the commit pin for openfermion.
=> Changing hydrogen chain multiplicity and openfermion dependency

README.md, examples/advanced_estimates.py, examples/h_chain_trotter.py, setup.cfg, src/benchq/problem_ingestion/__init__.py, src/benchq/problem_ingestion/molecule_instance_generation.py, tests/benchq/problem_ingestion/test_molecule_instance_generation.py
A number of users have encountered problems with installing PySCF. Some people don't actually need to use the benchq features that depend on PySCF, so making PySCF optional could be helpful. This PR moves the PySCF dependency into a `pyscf` install extra, and also bumps PySCF to the latest version (2.2.0). It also fixes some bugs that were causing a few of the examples to fail.
=> Make PySCF optional

src/benchq/problem_embeddings/_qsp.py, tests/benchq/problem_embeddings/test_qsp.py
This PR conssiderably improves the performance of `get_qsp_program` function. It does so by:
- avoiding creation of intermediate circuits
- avoding using circuit addition (instead relying on constructing needed operatiosn in advance)
- avoding `cirq.map_operations_and_unroll`
Unfornunately, benchmarks seems to be broken on `main`, but I tested the performance by profiling the following script and examing only the part of the execution tree corresponding to `get_qsp_program`. For this particular example, the introduced changes brought the execution time (when profiling) from ~151s to ~15s
```python
from benchq.algorithms import qsp_time_evolution_algorithm
from benchq.data_structures import ErrorBudget
from benchq.problem_ingestion import (
generate_jw_qubit_hamiltonian_from_mol_data,
) …
```
=> Improve performance of get qsp program

tests/benchq/resource_estimation/test_graph_compilation.py
After refactoring and switching to `graph_sim_mini` two of the resource estimation test cases stopped working and were consequently commented out. After discussing it with @AthenaCaesura we decided that the test cases should be restored with some adjustments to the expected results.
Additionally, this PR improves how the actual results are compared to the expected ones. Instead of comparing the items one by one (which terminates test case after first failure), we compare whole dictionaries, which gives us a detailed information of all failing comparisons at once.
The updates to the expected resource estimates are caused by differences in outputs between `graph_sim_mini` and previously used `Jabalizer`, and are described in detail below.
```python
circuit = Circuit([RX(np.pi / 4)(0), …
```
=> DTA-2 132/Adjust expected results for commented out test cases

src/benchq/resource_estimation/__init__.py, src/benchq/resource_estimation/_compute_lambda_sf.py, src/benchq/resource_estimation/openfermion_re.py, tests/benchq/resource_estimation/test_openfermion_re.py
Currently, the benchq integration with OpenFermion performs resource estimates on pyscf meanfield objects. However, we have several cases where we'd like to get OpenFermion resource estimates using only the molecular integrals. (For example, the HRL anti-corrosive instances and the L3-Zapata catalysis instances.)
This pull request refactors the OpenFermion integration to accept molecular integrals rather than a pyscf meanfield object.
For users who still wish to get resource estimates for pyscf objects, the one- and two-body integrals can be obtained as follows:
```python
from benchq.resource_estimation import get_single_factorized_qpe_resource_estimate
from openfermion.resource_estimates.molecule import pyscf_to_cas
h1, eri_full, _, _, _ = pyscf_to_cas(mean_field_object) …
```
=> OpenFermion estimates using ERI

src/benchq/__init__.py
Currently, jabalizer must be installed in order to use any part of the benchq Python API. This is because the automatic resource estimator is imported in the top-level package. This pull request addresses this by removing the automatic resource estimator from the top level.
=> Removing automatic resource estimator from top level package

src/benchq/data_structures/__init__.py, src/benchq/data_structures/resource_info.py, src/benchq/resource_estimation/azure.py, src/benchq/resource_estimation/graph/automatic_resource_estimator.py, src/benchq/resource_estimation/graph/customizable_pipelines.py, src/benchq/resource_estimation/graph/default_pipelines.py, src/benchq/resource_estimation/graph/extrapolation_estimator.py, src/benchq/resource_estimation/graph/graph_estimator.py, src/benchq/vizualization_tools.py, tests/benchq/resource_estimation/test_azure_re.py, tests/benchq/resource_estimation/test_extrapolation_estimation.py, tests/benchq/resource_estimation/test_graph_compilation.py
> **Warning**
> DON'T MERGE THIS PR UNTIL SCRIPTS ARE UPATED
This PR unifies all classes storing resource info into a single generic class. The attributes common to all (or at least most) resource info classes were preserved in `ResourceInfo`, and the differing attributes were pushed to a separate `extra` field. Type of the `extra` field is the generic parameter of `ResourceInfo`.
For instance, for `AzureResourceInfo`, there exists a `AzureExtra` class storing things like raw data, and `AzureResourceInfo` is just equal to `ResourceInfo[AzureExtra]`.
The PR also fixes Azure tests and applies several minor style improvements.
=> Clean up ResourceInfo class

src/benchq/data_structures/resource_info.py, src/benchq/resource_estimation/openfermion_re.py, tests/benchq/resource_estimation/test_openfermion_re.py
Currently, the OpenFermion resource estimator integration does not return the number of Toffoli gates. This pull request addresses this by introducing a `ResourceInfo` subclass for OpenFermion estimates that includes all the algorithm parameters returned by OpenFermion (including Toffoli count) in the `extra` attribute.
=> Adding openfermion resource info

setup.cfg, src/benchq/problem_embeddings/_trotter.py
- Context: orquestra-core requires orquestra-quantum=0.10.0. Installing benchq and orquestra-core together causes issues
- A [bug was caused](https://github.com/zapatacomputing/benchq/actions/runs/5269053218/jobs/9526621412?pr=84) in bumping to 0.10.0 because of [changing trotter_order to n_steps in time_evolution](https://github.com/zapatacomputing/orquestra-quantum/commit/78d4a682cf153e7c2197a3dcf428d4375cdf0d41). This PR also updates that syntax here in benchq
=> chore: bump orquestra quantum version

examples/ex_6_orquestra_customized/defs.py, examples/ex_6_orquestra_customized/run.py, src/benchq/data_structures/algorithm_implemenation.py
This pull request adds a new workflow example that runs resource estimation without using benchq pipelines. Instead of using pipelines, the workflow manually transpiles algorithm implementation into a graph representation, and then uses this graph representations to compute resource estimations two times.
Additionally, this PR makes `AlgorithmImplementation` class generic in its `program` field. This change does not affect benchq's behaviour at runtime, but makes the workflow much more readable, because one can see that the transpilation task transforms `AlgorithmImplementation[QuantumProgram]` into `AlgorithmImplementation[GraphPartition]`.
=> Implement new example workflow without pipelines

setup.cfg, src/benchq/data_structures/hardware_architecture_models.py
This simply makes `BasicArchitectureModel` a dataclass to address a problem reported by @1ethanhansen.
=> Make BasicArchitectureModel a dataclass

setup.cfg, src/benchq/data_structures/decoder.py
This will be useful for ZQS-1327
- Context: making DecoderModel a dataclass is useful for [ZQS-1327](https://github.com/zapatacomputing/benchq/tree/ZQS-1327-ability-to-log-benchq-params-to-mlflow)
- Added dataclass tag and replaced __init__ with just the list of params
[ZQS-1327]: https://zapatacomputing.atlassian.net/browse/ZQS-1327?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: turn DecoderModel into a dataclass

src/benchq/resource_estimation/graph/customizable_pipelines.py, src/benchq/resource_estimation/graph/extrapolation_estimator.py
When using custom pipelines for multiple parameters, the same graph was regenerated many times. To avoid that we now can only generate a single graph and reuse it
=> Feat: Enable graph data reuse in workflows

examples/ex_5_orquestra/defs.py, examples/ex_5_orquestra/run.py
- Context: There were multiple issues with example 5 due to some changes (some coming from the switch to CE):
- No longer able to directly instantiate `BasisArchitectureModel`s, so arbitrarily choose IonTrap
- Needing `stim` as a python import (still looking into why this happens and how to make it better for the user, see ZQS-1355
- New custom image
- `sdk.secrets.get` needs workspace and config specified
- Concise description of the implemented solution: see above for problems, fixes are fairly straightforward
- One note: I don't have any azure creds (`AZURE_CLIENT_ID`, `AZURE_TENANT_ID`, etc) so I haven't been able to ensure that the `azure_estimates` task is working. At least with this PR the `gsc_estimates` is guaranteed to work 😄
=> fix(docs): example 5

src/benchq/algorithms/ld_gsee.py, src/benchq/resource_estimation/openfermion_re.py, tests/benchq/resource_estimation/test_openfermion_re.py
For costing algorithms such as LD-GSEE, we need to obtain the cost of a single execution of the block-encoded Hamiltonian. This pull request addresses this by adding a function to get the cost (in terms of Toffoli gates and qubits) of the double factorized block encoding of electronic structure Hamiltonians.
=> Double factorized block encoding cost

src/benchq/resource_estimation/_footprint_analysis.py, tests/benchq/resource_estimation/test_openfermion_re.py
Right now, footprint analysis provided by `get_physical_cost` fails for large problems. This pull request addresses this by increasing the maximum code distance considered for logical data qubits. Additionally, if the physical costing fails, an exception will now be thrown to help users understand what has happened.
=> Increasing maximum data qubit code distance

.github/workflows/coverage.yml, .github/workflows/performance_test.yml, .github/workflows/style.yml, setup.cfg
In order to install benchq on Python versions later than 3.10, we need to remove the Python upper bound.
This PR:
- Removes the <3.11 constraint.
- Updated `orquestra-*` packages to the first release that supports Python 3.11.
=> chore: Remove Python 3.11 upper bound and bump orquestra-* packages

src/benchq/resource_estimation/_footprint_analysis.py, src/benchq/resource_estimation/openfermion_re.py
https://zapatacomputing.atlassian.net/browse/DTA2-304
1. Users would like to be able to choose the number of distillation factories that are running in parallel so that they can trade off the number of qubits and the runtime
2. Users would like to be able to view the values of n_physical_qubits_used_for_clifford_circuit and n_physical_qubits_used_for_distillation in the output of get_physical_cost
=> Feat: Add factory_count param to get_physical_cost and add distillation/computational qubit value for CostEstimate

src/benchq/decoder_modeling/decoder_resource_estimator.py, src/benchq/resource_estimators/graph_estimators/graph_estimator.py, tests/benchq/decoder_modeling/test_decoder_resource_estimator.py, tests/benchq/resource_estimation/graph_estimators/test_graph_estimator.py
This PR modifies the way that the logical qubit count is used in both graph state compilation resource estimates and decoder resource estimates. This was needed because the graph state compilation resource estimates were not consistently using 2*max_graph_degree (an approximation that will be updated in future pull requests) and the decoder resource estimates contained a bug where the number of logical qubits was being multiplied by two (a vestige from when all the BenchQ resource estimates assumed the bus architecture of GSC).
The implemented solution was to:
- compute the n_logical_qubit approximation once within the `estimate_resources_from_graph_data()` method and then use that value throughout
- remove the x2 from the decoder resource estimates so that it now accommodates any …
=> DTA2 176 actual decoder ests updates (minor changes)

src/benchq/magic_state_distillation/litinski_factories.py, tests/benchq/magic_state_distillation/test_litinski_factories.py, tests/benchq/resource_estimation/graph_estimators/test_graph_estimator.py
(https://zapatacomputing.atlassian.net/browse/DTA2-336)
Litinsky factory was returning based on input architecture type, not error rate. If someone changed/customised error_rate, they would get invalid fatories
=> Fix: Change litinsky factory to return based on error rate, not architecture type

src/benchq/resource_estimators/azure_estimator.py
Fixes #145 
Currently, for the Azure QRE integration, the error budget is being set to `azure_error_budget["tstates"]`. This results in an error because the error budget is expecting `tStates`.
Due to the integration with Azure QRE, automated test cases for validation is not easily done.
=> Fix: Update 'tStates' for Azure QRE error budget

setup.cfg
When I made my last PR to benchq. I Brian Goldsmith found that one of the examples had broken.
This was due to a bug in the sdk that was fixed in version 0.63.
This PR bumps the version of orquestra-sdk to require versions that have this fix.
=> fix: bump sdk version to avoid artifactfuture typing issue

examples/ex_3_packages_comparison.py
Fixes #154 
Currently, ex_3_packages_comparison.py is calling the azure_estimator and passing in `architecture_model=architecture_model`. However, the azure_estimator is expecting the parameter `hw_model`. 
To correct this behavior, there are two options:
1.) The first option is to change the parameter in the call to azure_estimator to `hw_model=architecture_model`. However, the azure_estimator does not currently handle hardware models. This is shown to the user in the following warning: 
`src/benchq/resource_estimators/azure_estimator.py:59: UserWarning: Supplying hardware model to AzureResourceEstimator is currently broken.`
Running a test using `hw_model` results in:
```
RuntimeError: Cannot retrieve results as job execution failed (IOError: cannot parse JSON: 'missing fields …
```
=> Fix: Example 3 Azure estimator paramter name

tests/benchq/compilation/test_rbs_with_pauli_tracking.py
Context: In the previous PR, some tests were skipped to enable all tests to pass. The purpose of this PR is to revive these skipped tests. 
Solution: @max-radin discovered that the errors were occurring during a qiskit transpilation pass. We determined that this transpilation likely only served to slightly speed up the simulation of the circuits and hence didn't impact the correctness of the test. This transpilation pass was simply removed, which enabled the previously failing tests to pass.
=> Removed unnecessary qiskit transpilation pass that was failing

src/benchq/resource_estimators/graph_estimator.py
Summary:
The issue involves removing the factor of 6 from BenchQ to correct inconsistencies in the runtime calculation.
Context:
This factor of six is because the syndrome extraction circuits have depth 6 when assuming direct physical ability to initialise and readout qubits in the X-basis. There is a discrepancy in the terminology used, which stems from the historical use of gate_time instead of surface_code_cycle_time.  The factor of six needs to be removed to align the equations with the updated terminology. 
Implemented solution:
Removed factor of 6 from time_per_circuit_in_seconds in graph_estimator.py in line 469
time_per_circuit_in_seconds = (
6 * num_cycles * hw_model.surface_code_cycle_time_in_seconds
)
=> Remove factor of 6
